### ISSUE TITLE
Create sphinx project for demos

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp-demos#1]
- [x] Make `./docs/conf.py` etc. `sphinx-quickstart` could help
- [x] Setup aiohttp theme for docs
- [x] Setup intersphinx mapping (see `./docs/conf.py` from aiohttp)
- [x] Add `./Makefile` with `make doc` and `make doc-spelling`. Borrow implementation from aiohttp
- [ ] Register the project on readthedocs
- [ ] Add `./.travis.yml` with docs check

**Comment by asvetlov** [comment]
@gyermolenko could you work on issue?
Feel free to ask my help if needed.

**Comment by gyermolenko** [comment]
Yes, I can do that in the nearest future
