### ISSUE TITLE
Demonstrate gunicorn usage

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp-demos#10]
Would be nice to have an ability to run the demo under gunicorn.
Need a gunicorn entrypoint file.
See https://stackoverflow.com/questions/47266296/running-aiohttp-server-using-gunicorn

**Comment by rocky1001** [comment]
Encountered same problem here, looking forward for the resolution, 
thanks a lot!

**Comment by asvetlov** [comment]
aiohttp 3.1 will allow using a coroutine as application factory: aio-llibs/aiohttp#2765
It makes adopting current demo code easier.
