### ISSUE TITLE
why run 'python init_db.py' show information that 'ModuleNotFoundError: No module named 'utils''??

### ISSUE THREAD

**Issue by lbsjsjob** [aio-libs/aiohttp-demos#110]
so confuse.
the polls example,why run 'python init_db.py' show information that 'ModuleNotFoundError: No module named 'utils''??

**Comment by lbsjsjob** [comment]
show that:
Traceback (most recent call last):
  File "d:\aiohttp-demos\demos\polls\init_db.py", line 4, in <module>
    from aiohttpdemo_polls.settings import BASE_DIR,get_config
  File "d:\aiohttp-demos\demos\polls\aiohttpdemo_polls\settings.py", line 6, in <module>
    from utils import TRAFARET
ModuleNotFoundError: No module named 'utils'

**Comment by gyermolenko** [comment]
Let's start with clean virtualenv. Do the following and show me the output
```
$ cd demos/polls
$ pip install -e .
$ pip list
```

**Comment by Dreamsorcerer** [comment]
The import line that is failing, does not look like that in the repo:
https://github.com/aio-libs/aiohttp-demos/blob/master/demos/polls/aiohttpdemo_polls/settings.py#L7

Repo code is:
`from aiohttpdemo_polls.utils import TRAFARET`
Traceback says:
`from utils import TRAFARET`

So, it looks like you must have edited the files (given that line was last edited 3 years ago).

I suspect you didn't know how to run the application originally, and modified the imports to hack around it.
Try running the application with `python -m aiohttpdemo_polls`.
