### ISSUE TITLE
Setup travis for running tests for demos

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp-demos#2]
Also add `make test` command etc -- as we have for aiohttp.

**Comment by jettify** [comment]
I added flake8 checker for started https://github.com/aio-libs/aiohttp-demos/pull/5

**Comment by gyermolenko** [comment]
made an attempt on it in #27

**Comment by gyermolenko** [comment]
There are .travis and makefile test commands.
There is also #20 to add tests for chat demo. 
Can we close this issue @asvetlov ?

**Comment by asvetlov** [comment]
I think yes
