### ISSUE TITLE
Create simple blog demo

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiohttp-demos#25]
I bet someone has code to share, would be nice to see blog demo here.

**Comment by Arfey** [comment]
I will try to do it

**Comment by gyermolenko** [comment]
Oh hi.
Also thought about doing it this week. (just began and came here to comment the same thing :)

**Comment by Arfey** [comment]
so, what?

**Comment by gyermolenko** [comment]
hi, @Arfey . Couldn't tag you in PR itself. Would appreciate your feedback on #33

**Comment by gyermolenko** [comment]
basic blog demo project was created in scope of #33 
In future It could be improved with tags, subscriptions, css styles, flash messages etc. - good candidates for `first timer issue` tags for completely new people who would like to contribute
