### ISSUE TITLE
Create graphQl example

### ISSUE THREAD

**Issue by Arfey** [aio-libs/aiohttp-demos#31]
GraphQl is very popular, so i think it is good idea show how look simple GraphQL api.

What i want to do:

- [x] create graphQl api

- [x] add graphIQl view for interactive work with data

- [ ] add tests

Does anyone have a suggestion before I start?

**Comment by asvetlov** [comment]
Perfect idea!
Please make a scratch for providing a basement for discussion.
I'd like to review at least the overall design first.

**Comment by asvetlov** [comment]
Awesome!

**Comment by jettify** [comment]
We have large GraphQL example merged!
