### ISSUE TITLE
Create simple demo of slack bot

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiohttp-demos#34]

**Comment by pavloshushkov** [comment]
> _No description provided._

 has taken up the challenge

**Comment by jettify** [comment]
We have demo of `moderator.ai`, basically toxic comments classifier, we can reuse model from there.  Slack bot can react on message and try to detect if message insulting or toxic, if so post cat image and ask author to be polite.

**Comment by jettify** [comment]
This is just bot idea for demo not a requirement :)

**Comment by hzlmn** [comment]
@jettify Created simple bot. It use slack HTTP Events API and model from moderator. On toxic message it send random GIF of cat from giphy api :) Pretty dirty reviews welcome, if idea ok i will continue polishing of it https://github.com/hzlmn/moderator_bot. Also do you consider as a better approach sockets api, cuz slack provide it as well?

**Comment by jettify** [comment]
@hzlmn your bot looks awesome! Can you please update our README file and add your project there with picture and reference to your github?

**Comment by hzlmn** [comment]
@jettify I can submit PR if it's reasonable. I have created separate repo just for testing purposes :)

**Comment by jettify** [comment]
You can add demo code here or reference it from README, what ever works for you.

**Comment by Arfey** [comment]
I think, add code to the repo better than add only reference to the README.
