### ISSUE TITLE
Create simple machine learning demo, serve prediction results with aiohttp

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiohttp-demos#35]
I have working code of very simple API with react UI, that classifies offensive and toxic comments. I think it should be good addition for aiohttp use cases. I still need to do some clean up, after will copy app here.

https://github.com/jettify/moderator.ai

**Comment by asvetlov** [comment]
Looks interesting.
I have no idea why yarn is required though.

**Comment by jettify** [comment]
yarn is fancy way to build to install dependencies and build react app.

**Comment by Arfey** [comment]
u have `package-lock.json` it's `npm` and `yarn.lock` it's `yarn`. use something one 😀

**Comment by jettify** [comment]
Good catch I accidentally committed that.

**Comment by Arfey** [comment]
Also, u can make build in a computer and commit `bundle` files. It remove step with `yarn install` and `make build`. Yes it's bad practice for front-end but example for back-end, right?

**Comment by jettify** [comment]
https://github.com/aio-libs/aiohttp-demos/pull/37
