### ISSUE TITLE
Defining model

### ISSUE THREAD

**Issue by djKooks** [aio-libs/aiohttp-demos#38]
Hello,
I'm currently referring polls demo for developing aiohttp server app.
One question is, there are guide about defining model in tutorial document, and it said model can be defined as class instead of using table.
```
class Question(Base):
    __tablename__ = 'question'

    id = Column(Integer, primary_key=True)
    question_text = Column(String(200), nullable=False)
    pub_date = Column(Date, nullable=False)
```
Is there any sample to develop in this way?

Thanks.

**Comment by asvetlov** [comment]
Please create a pull request.
We discussed the subject with @gyermolenko about a year ago, pushing the decision into the docs makes sense.

**Comment by djKooks** [comment]
@asvetlov Okay, got it.
