### ISSUE TITLE
graphQL example gif file slows down browser tab

### ISSUE THREAD

**Issue by supadrupa** [aio-libs/aiohttp-demos#43]
Size of the gif file is 11.8 MB and dimensions are 3360x2100 pixels

**Comment by Arfey** [comment]
PR welcome.

**Comment by bigboynaruto** [comment]
I'm working on it.

**Comment by webknjaz** [comment]
I suggest plugging https://github.com/apps/imgbot instead of manual human work.

**Comment by Arfey** [comment]
is it working for gif files?

**Comment by webknjaz** [comment]
It's not explicitly stated in docs https://imgbot.net/docs, but I'd expect it to.

**Comment by webknjaz** [comment]
Other point would be that gifs might be hard to compress losslessly.

**Comment by bigboynaruto** [comment]
I'll try it, because manual approach doesn't seem to work, since the file is too large - online tools fail and local tool on my computer (ImageMagic) runs out of memory.

**Comment by webknjaz** [comment]
@Arfey has privileges to enable it on this repo, but you @bigboynaruto can try it on your fork

**Comment by webknjaz** [comment]
(or @jettify/@asvetlov)
