### ISSUE TITLE
Unclear where to put example code from "Creating connection engine" part

### ISSUE THREAD

**Issue by nomhoi** [aio-libs/aiohttp-demos#64]
На этой странице https://aiohttp-demos.readthedocs.io/en/latest/tutorial.html
Начиная с раздела Databases::Creating connection engine непонятно в какие файлы вставлять код, приходится смотреть сюда. И с раздела Templates все сыпется.

Это специально чтобы отпугнуть начинающих изучать фреймворк?

**Comment by kxepal** [comment]
Там по контексту должно быть понятно что и куда, если не вырывать сниппеты из документации. А так же в репозитории присутствует полная реализация этого самого туториала. Вроде ничего сложного, чтобы должно отпугнуть. Но если такое все нашлось - patches welcome!

**Comment by gyermolenko** [comment]
@nomhoi 
Нет, это не специально.

А куски кода в "Creating connection engine" - отсюда:
https://github.com/aio-libs/aiohttp-demos/blob/master/demos/polls/aiohttpdemo_polls/db.py#L36
https://github.com/aio-libs/aiohttp-demos/blob/master/demos/polls/aiohttpdemo_polls/main.py#L25

Как дельно предложил **kxepal** - есть возможность улучшить.

**Comment by nomhoi** [comment]
> Там по контексту должно быть понятно что и куда, если не вырывать сниппеты из документации. 
А так же в репозитории присутствует полная реализация этого самого туториала. Вроде ничего сложного, чтобы должно отпугнуть. Но если такое все нашлось - patches welcome!

**Comment by nomhoi** [comment]
> Там по контексту должно быть понятно что и куда, если не вырывать сниппеты из документации. 

Я решил не скачивать сразу все исходники и сделать все шаг за шагом, как это предлагается в документации.

> А так же в репозитории присутствует полная реализация этого самого туториала. 

Про это есть в документации, в самом начале.

> Вроде ничего сложного, чтобы должно отпугнуть. 

Это да, мне удалось пробиться. Скачал проект из репозитории и запустил. Правда пришлось переместить main.py в папку выше.

> Но если такое все нашлось - patches welcome!

Пока ничего не буду патчить, пока изучаю.

**Comment by nomhoi** [comment]
> Нет, это не специально.

Вот пример замечательной документации: 
https://code.visualstudio.com/docs/python/tutorial-django#getstarted-articles

1. Когда мы выполняем шаг за шагом предлагаемые действия, то к концу туториала мы должны получить тот-же код, который предлагается на гитхабе, чего не наблюдается.
По туториалу с самого начала мы запускаем сервер с помощью python main.py, если находимся в папке aiohttpdemo_polls, или aiohttpdemo_polls/main.py, если находимся в pools. И это работает в начале.
С раздела Templates уже не работает, потому что нужно запускать с помощью команды python -m aiohttpdemo_polls, и все равно не будет работать, потому что еще нет нужного файла __main__.py.

2. В туториале в одном месте указано from models import question, choice - нет такого модуля, есть db.

3. Про то, что в конце раздела Database не указываются куда какой код добавлять - уже ранее написал.

В общем, туториал производит жуткое впечатление.

**Comment by gyermolenko** [comment]
@nomhoi спасибо за замечания, поправлю
