### ISSUE TITLE
Imagetagger demo app failing while  "Make run" command

### ISSUE THREAD

**Issue by SaddamBInSyed** [aio-libs/aiohttp-demos#83]
Hi.

Long story in short:

I carefully followed the instruciton provided in the document and when I run the Make run command then I am getting the below error.

aiohttp-keras-demo$ make run
python -m image tagger
make: python: Command not found
Makefile:34: recipe for target 'run' failed
make: *** [run] Error 127

environment:

python 3.6.8
ubuntu os onb VMware.

please advise .

**Comment by gyermolenko** [comment]
Let's try to figure it out. It might as well be an issue with documentation.

1. create clean virtual environment

2. `$ cd aiohttp-demos/demos/imagetagger`

3. `$ pip install -r requirements/development.txt`

4. `$ python -m imagetagger`

Here is what I got:
```
Using TensorFlow backend.
2019-10-14 17:56:58.674769: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-14 17:56:58.709824: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f963a3db1a0 executing computations on platform Host. Devices:
2019-10-14 17:56:58.710051: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
/Users/.../aiohttp-demos-3.7.4/lib/python3.7/site-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
======== Running on http://127.0.0.1:8000 ========
(Press CTRL+C to quit)
```

Please execute steps above and reply with your output.

**Comment by SaddamBInSyed** [comment]
hi @gyermolenko ,

I have changed '**python3** -m imagetagger"  instead of "python -m imagetagger". since I am using py3.6.

now all fine.

thanks for the response.
