### ISSUE TITLE
Error running ImageTagger demo app.

### ISSUE THREAD

**Issue by SaddamBInSyed** [aio-libs/aiohttp-demos#84]
Hi.

I am trying to run the aiohttp - demo (ImageTagger) project in PyCharm 2019.x but it throwing some errors like below,

Error 1 :
Using TensorFlow backend.
C:\Users\saddam.X.XXXX\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

Error 2:
ImportError: cannot import name 'routes'
etc...

Can anyone guide me on how to run this ImageTagger app?

Environment"

Ubuntu on Vmware.
python3.6

**Comment by gyermolenko** [comment]
see #83
